# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0010_auto_20180609_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='reward',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
