# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0017_move_bans_to_cache_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bancache',
            name='cache_version',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
